[project]
name = "claude-agent-sdk-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "claude-agent-sdk>=0.1.4",
    "ipykernel>=7.0.1",
]

[tool.uv.workspace]
members = ["deep-research"]
